name: QA-Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Setup the environment
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # Lint with Flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          make lint

      # Run unit tests
      - name: Unit testing
        run: |
          make unit-test
